service:
  name: aws-lambda-with-dynamo-db

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
      Resource: "arn:aws:dynamodb:eu-west-1:accountId:table/to-do-list"

functions:
  saveToDoItem:
    handler: handler.saveToDoItem
    events:
      - http:
          method: post
          path: save-to-do-item
          cors: true
  getToDoItem:
    handler: handler.getToDoItem
    events:
      - http:
          method: get
          path: to-do-items/{id}
          cors: true

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
