service:
  name: aws-lambda-with-dynamo-db

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  region: eu-west-1

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          method: get
          path: hello

resources:
  # DynamoDB
  - ${file(resources/dynamodb-table.yml)}
